#!/bin/bash

echo "hi"
input="./math.txt"

# IFS to keep leading or trailing whitespce to be trimmed
while IFS= read -r var
do
  echo "$var"
done < "$input"

array=(34 56 12 31)
for i in "${array[@]}"; do echo "$i"; done | sort -n
